import sys
sys.path.append('/Users/namduong/Code/back-end-search/')
from elasticsearch import Elasticsearch
from config.config_handling import get_config_value


def connect_elasticsearch(**kwargs):
    # Found in the 'Manage Deployment' page
    _es_cloud_id = get_config_value('elastic', 'es_cloud_id')
    # Password for the 'elastic' user generated by Elasticsearch
    _es_password = get_config_value('elastic', 'es_password')
    if 'cloud_id' in kwargs.keys():
        _es_hosts = kwargs['cloud_id']
    # Create the client instance
    _es_client = Elasticsearch(
        cloud_id=_es_cloud_id,
        basic_auth=("elastic", _es_password)
    )
    if _es_client.ping():
        print('Yay Connect')
    else:
        print('Awww it could not connect!')
    return _es_client


